src/Entity/Proveedor.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProveedorRepository")
 */
class Proveedor
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="integer")
     */
    private $codigo_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $localidad;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     */
    private $telefono;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Pedido", mappedBy="id_proveedor")
     */
    private $id_pedido;

    public function __toString(){
        return $this->nombre;
    }

    public function __construct()
    {
        $this->id_pedido = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getCodigoPostal(): ?int
    {
        return $this->codigo_postal;
    }

    public function setCodigoPostal(int $codigo_postal): self
    {
        $this->codigo_postal = $codigo_postal;

        return $this;
    }

    public function getLocalidad(): ?string
    {
        return $this->localidad;
    }

    public function setLocalidad(string $localidad): self
    {
        $this->localidad = $localidad;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelefono(): ?int
    {
        return $this->telefono;
    }

    public function setTelefono(int $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    /**
     * @return Collection|Pedido[]
     */
    public function getIdPedido(): Collection
    {
        return $this->id_pedido;
    }

    public function addIdPedido(Pedido $idPedido): self
    {
        if (!$this->id_pedido->contains($idPedido)) {
            $this->id_pedido[] = $idPedido;
            $idPedido->setIdProveedor($this);
        }

        return $this;
    }

    public function removeIdPedido(Pedido $idPedido): self
    {
        if ($this->id_pedido->contains($idPedido)) {
            $this->id_pedido->removeElement($idPedido);
            // set the owning side to null (unless already changed)
            if ($idPedido->getIdProveedor() === $this) {
                $idPedido->setIdProveedor(null);
            }
        }

        return $this;
    }
}

src/Form/ProveedorType.php
<?php

namespace App\Form;

use App\Entity\Proveedor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProveedorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre')
            ->add('codigo_postal')
            ->add('localidad')
            ->add('email')
            ->add('telefono', TextType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Proveedor::class,
        ]);
    }
}

src/Controller/ProveedorController.php
<?php

namespace App\Controller;

use App\Entity\Proveedor;
use App\Form\ProveedorType;
use App\Repository\ProveedorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/proveedor")
 */
class ProveedorController extends AbstractController
{
    /**
     * @Route("/", name="proveedor_index", methods={"GET"})
     */
    public function index(ProveedorRepository $proveedorRepository): Response
    {
        return $this->render('proveedor/index.html.twig', [
            'proveedors' => $proveedorRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="proveedor_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $proveedor = new Proveedor();
        $form = $this->createForm(ProveedorType::class, $proveedor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($proveedor);
            $entityManager->flush();
            $this->addFlash('new_proveedor','Proveedor -'.strtolower($proveedor->getNombre()).'- creado con éxito.');

            return $this->redirectToRoute('proveedor_index');
        }

        return $this->render('proveedor/new.html.twig', [
            'proveedor' => $proveedor,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="proveedor_show", methods={"GET"})
     */
    public function show(Proveedor $proveedor): Response
    {
        return $this->render('proveedor/show.html.twig', [
            'proveedor' => $proveedor,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="proveedor_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Proveedor $proveedor): Response
    {
        $form = $this->createForm(ProveedorType::class, $proveedor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('proveedor_index');
        }

        return $this->render('proveedor/edit.html.twig', [
            'proveedor' => $proveedor,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="proveedor_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Proveedor $proveedor): Response
    {
        if ($this->isCsrfTokenValid('delete'.$proveedor->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($proveedor);
            $entityManager->flush();
            $this->addFlash('delete_proveedor','Proveedor -'.strtolower($proveedor->getNombre()).'- eliminado con éxito.');
        }
        return $this->redirectToRoute('proveedor_index');
    }
}

templates/proveedor/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div id="botones_editar">
        <button id="boton" class="btn">{{ button_label|default('Añadir') }}</button>
{{ form_end(form) }}

templates/proveedor/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar - Proveedor{% endblock %}

{% block body %}
<div id="form_proveedor_new_edit">
    {{ include('proveedor/_form.html.twig', {'button_label': 'Actualizar'}) }}
    <button id="volver" class="btn" onclick="window.close()">Volver</button>
    </div>
</div>
{% endblock %}

templates/proveedor/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestiona JMJ{% endblock %}

{% block body %}

    {% for flash_message in app.session.flashbag.get('new_proveedor') %}
        <div class="alert alert-success" role="alert">
            {{ flash_message }}
        </div>
    {% endfor %}

        {% for flash_message in app.session.flashbag.get('delete_proveedor') %}
        <div class="alert alert-danger" role="alert">
            {{ flash_message }}
        </div>
    {% endfor %}


    <h3>Proveedores</h3>

    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Código Postal</th>
                <th>Localidad</th>
                <th>Email</th>
                <th>Teléfono</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for proveedor in proveedors %}
            <tr class="hover_fila">
                <td>{{ proveedor.nombre }}</td>
                <td>{{ proveedor.codigoPostal }}</td>
                <td>{{ proveedor.localidad }}</td>
                <td>{{ proveedor.email }}</td>
                <td>{{ proveedor.telefono }}</td>
                <td class="celda_edit"><input type="image" class="icono_editdelete" src="/img/icono-editar.svg" onclick="window.open('{{ path('proveedor_edit', {'id': proveedor.id}) }}','', ',height=600,width=600,left=500,top=60')"></td>
                <td class="celda_delete">{{ include('proveedor/_delete_form.html.twig') }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">No hay proovedores registrados.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


<input type="image" class="add_icono" src="/img/plus-circle-solid.svg" onclick="window.location.href='{{ path('proveedor_new') }}'">
{% endblock %}

templates/proveedor/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nuevo - Proveedor{% endblock %}

{% block body %}
 
    <div id="form_proveedor_new_edit">
    {{ include('proveedor/_form.html.twig') }}
    <button id="volver" class="btn" onclick="window.location.href='{{ path('proveedor_index') }}'">Volver</button>

{% endblock %}


{% block javascripts %}
    <script src="{{ asset('/js/telefono_validacion.js') }}"></script>
{% endblock %}