src/Entity/LineaPedido.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LineaPedidoRepository")
 */
class LineaPedido
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $unidades;

    /**
     * @ORM\Column(type="float")
     */
    private $precio_linea;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Articulo", inversedBy="id_lineapedido")
     */
    private $id_articulo;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Pedido", inversedBy="id_lineapedido")
     */
    private $id_pedido;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUnidades(): ?int
    {
        return $this->unidades;
    }

    public function setUnidades(int $unidades): self
    {
        $this->unidades = $unidades;

        return $this;
    }

    public function getPrecioLinea(): ?float
    {
        return $this->precio_linea;
    }

    public function setPrecioLinea(float $precio_linea): self
    {
        $this->precio_linea = $precio_linea;

        return $this;
    }

    public function getIdArticulo(): ?Articulo
    {
        return $this->id_articulo;
    }

    public function setIdArticulo(?Articulo $id_articulo): self
    {
        $this->id_articulo = $id_articulo;

        return $this;
    }

    public function getIdPedido(): ?Pedido
    {
        return $this->id_pedido;
    }

    public function setIdPedido(?Pedido $id_pedido): self
    {
        $this->id_pedido = $id_pedido;

        return $this;
    }
}

src/Entity/Pedido.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PedidoRepository")
 */
class Pedido
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_pedido;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_entrega;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Proveedor", inversedBy="id_pedido")
     */
    private $id_proveedor;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LineaPedido", mappedBy="id_pedido")
     */
    private $id_lineapedido;

    public function __construct()
    {
        $this->id_lineapedido = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFechaPedido(): ?\DateTimeInterface
    {
        return $this->fecha_pedido;
    }

    public function setFechaPedido(\DateTimeInterface $fecha_pedido): self
    {
        $this->fecha_pedido = $fecha_pedido;

        return $this;
    }

    public function getFechaEntrega(): ?\DateTimeInterface
    {
        return $this->fecha_entrega;
    }

    public function setFechaEntrega(\DateTimeInterface $fecha_entrega): self
    {
        $this->fecha_entrega = $fecha_entrega;

        return $this;
    }

    public function getIdProveedor(): ?Proveedor
    {
        return $this->id_proveedor;
    }

    public function setIdProveedor(?Proveedor $id_proveedor): self
    {
        $this->id_proveedor = $id_proveedor;

        return $this;
    }

    /**
     * @return Collection|LineaPedido[]
     */
    public function getIdLineapedido(): Collection
    {
        return $this->id_lineapedido;
    }

    public function addIdLineapedido(LineaPedido $idLineapedido): self
    {
        if (!$this->id_lineapedido->contains($idLineapedido)) {
            $this->id_lineapedido[] = $idLineapedido;
            $idLineapedido->setIdPedido($this);
        }

        return $this;
    }

    public function removeIdLineapedido(LineaPedido $idLineapedido): self
    {
        if ($this->id_lineapedido->contains($idLineapedido)) {
            $this->id_lineapedido->removeElement($idLineapedido);
            // set the owning side to null (unless already changed)
            if ($idLineapedido->getIdPedido() === $this) {
                $idLineapedido->setIdPedido(null);
            }
        }

        return $this;
    }
}

src/Form/PedidoType.php
<?php

namespace App\Form;

use App\Entity\Pedido;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PedidoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('fecha_entrega',DateType::class,array(
                'widget' => 'single_text',
                'input_format' => 'd-m-Y',
                'years' => range(date('Y'),date('Y')-100),
                'months' => range(1,12),
                'days' => range(1,31),
                'label' => 'Fecha de Entrega'
            ))
            ->add('id_proveedor',null,[
                'label' => 'Proveedor',
                'multiple' => false,
                'expanded' => false,
                'required' => true,
                'label_attr' =>['class' => 'proveedor'],
                //'required' => true,
                'placeholder' => 'Seleccione un proveedor'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            
        ]);
    }
}

src/Controller/PedidoController.php
<?php

namespace App\Controller;

use App\Entity\Pedido;
use App\Entity\LineaPedido;
use App\Form\PedidoType;
use App\Form\LineaPedidoType;
use App\Repository\PedidoRepository;
use App\Repository\LineaPedidoRepository;
use App\Repository\ArticuloRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use \PDO; 

/**
 * @Route("/pedido")
 */
class PedidoController extends AbstractController
{
    /**
     * @Route("/", name="pedido_index", methods={"GET"})
     */
    public function index(PedidoRepository $pedidoRepository , LineaPedidoRepository $lineaPedidoRepository): Response
    {
        $pedido = new Pedido();
        $form_pedido = $this->createForm(PedidoType::class, $pedido, [
            'action' => $this->generateUrl('pedido_new'),
            'method' => 'POST',
        ]);

        $linea_pedido = new LineaPedido();
        $form_linea = $this->createForm(LineaPedidoType::class, $linea_pedido, [
            'action' => $this->generateUrl('linea_pedido_new'),
            'method' => 'POST',
        ]);

        return $this->render('pedido/index.html.twig', [
            'pedidos' => $pedidoRepository->findAll(),
            'linea_pedidos' => $lineaPedidoRepository->findAll(),
            'pedido' => $pedido,
            'form_pedido' => $form_pedido->createView(),
            'linea_pedido' => $linea_pedido,
            'form_linea' => $form_linea->createView(),
        ]);
    }

    /**
     * @Route("/new", name="pedido_new", methods={"GET","POST"})
     */
    public function new(Request $request,\Swift_Mailer $mailer, LineaPedidoRepository $lineaPedidoRepository, ArticuloRepository $articuloRepository): Response
    {
        $pedido = new Pedido();
        $form = $this->createForm(PedidoType::class, $pedido);
        $form->handleRequest($request);
        
        $fechaActual = getDate();
        $dia = $fechaActual['mday'];
        $mes = $fechaActual['mon'];
        $year = $fechaActual['year'];
        $fechaFormat = $dia.'-'.$mes.'-'.$year;
        $fecha = DateTime::createFromFormat('d-m-Y', $fechaFormat);
        $pedido->setFechaPedido($fecha);

        if ($form->isSubmitted() && $form->isValid()) { 
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($pedido);
            $entityManager->flush();

            /* Envío de correo electrónico */
            $form = $form->getData();

            /* Datos del pedido */
            $fecha_pedido = $pedido->getFechaPedido();
            $fecha_entrega = $pedido->getFechaEntrega();
            $id_proveedor = $pedido->getIdProveedor();

            $productos="<table border='1' style='text-align:center;'><tr><th>Artículo</th><th>Unidades</th><th>Precio</th></tr>";
            $style = " width='100' height='50'";

            $resultado=$lineaPedidoRepository->findAll();
            foreach($resultado as $linea){
                $productos .= '<tr><td'.$style.'>'.$linea->getIdArticulo().'</td><td'.$style.'>'.$linea->getUnidades().'</td><td'.$style.'>'.$linea->getPrecioLinea().'€</td></tr>';
            }
            $productos.='</table>';
        
            $mensaje = (new \Swift_Message('Nuevo pedido de Restaurante JMJ '))
                ->setFrom(['restaurantejmj@gmail.com' => 'Restaurante JMJ'])
                ->setTo('restaurantejmj@gmail.com')
                ->setBody(
                    'Fecha de pedido: '.date_format($fecha_pedido, 'd-m-Y').
                    '<br>Fecha de entrega: '.date_format($fecha_entrega, 'd-m-Y').
                    '<br>Proveedor: '.$id_proveedor.
                    '<br><br><h3><u>ALBARÁN:</u></h3> '.$productos
                    , 'text/html')
            ;

            $mailer->send($mensaje);
            
            $em = $this->getDoctrine()->getManager();
            $connection = $em->getConnection();
            
            /* Aumentar existencias stock */
            $articulos=$articuloRepository->findAll();
            $lineas=$lineaPedidoRepository->findAll();
           
            for($i=0;$i<count($articulos);$i++){
                for($j=0;$j<count($lineas);$j++){
                   if($lineas[$j]->getIdArticulo()==$articulos[$i]->getNombre()){
                        $total =  $articulos[$i]->getExistencias()+$lineas[$j]->getUnidades();
                        $nombreart = $lineas[$j]->getIdArticulo();
                        $statement = $connection->prepare("UPDATE articulo SET existencias=:total WHERE nombre=:nombreart");
                        $statement->bindParam(":nombreart",$nombreart);
                        $statement->bindParam(":total",$total);
                        $statement->execute();
                    }
                }
            }
        
            /* Eliminar línas */ 
            $statement = $connection->prepare("DELETE FROM linea_pedido");
            $statement->execute();

            $this->addFlash('new_pedido','Pedido con identificación -'.$pedido->getId().'- creado con éxito.');
            return $this->redirectToRoute('pedido_index');
        }
        
    }

    /**
     * @Route("/{id}", name="pedido_show", methods={"GET"})
     */
    public function show(Pedido $pedido): Response
    {
        return $this->render('pedido/show.html.twig', [
            'pedido' => $pedido,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="pedido_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Pedido $pedido): Response
    {
        $form_pedido = $this->createForm(PedidoType::class, $pedido);
        $form_pedido->handleRequest($request);

        if ($form_pedido->isSubmitted() && $form_pedido->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('pedido_index');
        }

        return $this->render('pedido/edit.html.twig', [
            'pedido' => $pedido,
            'form_pedido' => $form_pedido->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pedido_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Pedido $pedido): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pedido->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($pedido);
            $entityManager->flush();
            $this->addFlash('delete_pedido','Pedido con identificación -'.$pedido->getId().'- eliminado con éxito.');
        }

        return $this->redirectToRoute('pedido_index');
    }
}

templates/pedido/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar - Pedido{% endblock %}

{% block body %}
    <div id="form_pedido_edit">
        {{ include('pedido/_form.html.twig', {'button_label': 'Actualizar'}) }}
        <button id="volver" class="btn" onclick="location.href='{{ path('pedido_index') }}'">Volver</button>
        </div>
    </div>
    <script>
    document.getElementById('pedido_aviso').style.visibility="hidden";
    </script>
{% endblock %}

templates/pedido/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestiona JMJ{% endblock %}

{% block body %}

    {% for flash_message in app.session.flashbag.get('new_pedido') %}
        <div class="alert alert-success" role="alert">
            {{ flash_message }}
        </div>
    {% endfor %}

    {% for flash_message in app.session.flashbag.get('delete_articulo') %}
        <div class="alert alert-danger" role="alert">
            {{ flash_message }}
        </div>
    {% endfor %}

    <h3>Registro</h3>

    <table class="table">
        <thead>
            <tr>
                <th>Número de Pedido</th>
                <th>Proveedor</th>
                <th>Fecha de pedido</th>
                <th>Fecha de entrega</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for pedido in pedidos %}
        
            <tr>
                <td>{{ pedido.id }}</td>
                <td>{{ pedido.getIdProveedor }}</td>
                <td>{{ pedido.fechaPedido ? pedido.fechaPedido|date('d-m-Y') : '' }}</td>
                <td>{{ pedido.fechaEntrega ? pedido.fechaEntrega|date('d-m-Y') : '' }}</td>
                <td class="celda_edit"><input type="image" class="icono_editdelete" src="/img/icono-editar.svg" onclick="window.open('{{ path('pedido_edit', {'id': pedido.id}) }}','', ',height=600,width=600,left=500,top=60')"></td>
                <td class="celda_delete">{{ include('pedido/_delete_form.html.twig') }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">No hay pedidos registrados</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <!-- Linea de Pedido -->
    <br>
    <br>
    <br>
    <h3>Líneas de pedido</h3>

    <table id="tabla_linea" class="table">
        <thead>
            <tr>
                <th>Número de línea</th>
                <th>Artículo</th>
                <th>Unidades</th>
                <th>Precio Total</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for linea_pedido in linea_pedidos %}
            <tr>
                <td>{{ linea_pedido.id }}</td>
                <td>{{ linea_pedido.getIdArticulo() }}</td>
                <td>{{ linea_pedido.unidades }}</td>
                <td>{{ linea_pedido.precioLinea }}€</td>
                <td class="celda_edit"><input type="image" class="icono_editdelete" src="/img/icono-editar.svg" onclick="window.open('{{ path('linea_pedido_edit', {'id': linea_pedido.id}) }}','', ',height=600,width=600,left=500,top=60')"></td>
                <td class="celda_delete">{{ include('linea_pedido/_delete_form.html.twig') }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">No hay líneas de pedido registradas</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="nuevo_form_linea">
    <h6><b>Nueva línea de pedido</b></h6>
    {{ include('linea_pedido/_form.html.twig') }}
    </div>
    </div>

    <div class="nuevo_form_pedido">
    <h6><b>Realizar pedido</b></h6>
    {{ include('pedido/_form.html.twig') }}
    </div>
    </div>

    <!-- Validación líneas de pedido para poder hacerlo -->
    <script>
        var tabla = document.getElementById('tabla_linea');
        var celda = tabla.getElementsByTagName('td');
        var boton = document.getElementById('boton');
        var aviso = document.getElementById('pedido_aviso');

        if(celda[0].innerHTML != "No hay líneas de pedido registradas"){
            boton.disabled = false;
            aviso.style.visibility = "hidden";
        }else{
            boton.disabled = true;
            aviso.style.visibility = "visible";
        }
    </script>

    <!-- Validación fecha de pedido -->
    <script>
        var fecha_input = document.getElementById('pedido_fecha_entrega');
    
        fecha_input.addEventListener('blur',function(){

            var fecha = new Date();

            var mes = (fecha.getMonth() + 1).toString();

            if (mes.length <=1 ) {
                mes = "0" + mes;
            }

            var dia = fecha.getDate().toString();

            if (dia.length <=1 ) {
                dia = "0" + dia;
            }

            var anio = fecha.getFullYear().toString();

            var fecha_actual = fecha.getFullYear() + "-" + mes + "-" + dia;

            var fecha_pedido = new Date(anio, mes, dia);
            
            var fecha_entrega = new Date(fecha_input.value.substring(0,4), fecha_input.value.substring(5,7), fecha_input.value.substring(8,10));

            if( fecha_input.value <= fecha_actual){
                alert('Fecha de entrega anterior o igual a la fecha de pedido!!');
                fecha_input.value = "";
            }else if( fecha_entrega.getMonth() > (fecha_pedido.getMonth()+2) ){
                alert('La fecha de entrega no puede ser superior a 2 meses de la fecha de pedido.');
                fecha_input.value = "";
            }else if( fecha_entrega.getMonth() == (fecha_pedido.getMonth()+2) && fecha_entrega.getDate() > fecha_pedido.getDate() ){
                alert('La fecha de entrega no puede ser superior a 2 meses de la fecha de pedido.');
                fecha_input.value = "";
            }else if( fecha_entrega.getMonth() == (fecha_pedido.getMonth()+2) && fecha_entrega.getFullYear() > fecha_pedido.getFullYear() ){
                alert('La fecha de entrega no puede ser superior a 2 meses de la fecha de pedido.');
                fecha_input.value = "";
            }else if( fecha_entrega.getFullYear() > fecha_pedido.getFullYear() ){
                alert('La fecha de entrega no puede ser superior a 2 meses de la fecha de pedido.');
                fecha_input.value = "";
            }
        })
    </script>

{% endblock %}

{% block javascripts %}
    <script src="{{ asset('/js/unidades_pedido_validacion.js') }}"></script>
{% endblock %}